-- Testbench of Simple Combinatorial Circuit for Lab 1
-- AIT EV Digital Circuit 2 (2025)
-- Do not edit this file

library IEEE;
use IEEE.std_logic_1164.ALL;
use std.env.ALL;

entity logic1_tb is
end logic1_tb;

architecture sim of logic1_tb is
component logic1 is
    port ( L, M, N : in  std_ulogic;
           X       : out std_ulogic);
end component;
signal L, M, N, X : std_ulogic;

begin
    L1 : logic1 port map ( L, M, N, X );

    process begin
        L <= '0'; M <= '0'; N <= '0'; wait for 50 ns;
        L <= '0'; M <= '0'; N <= '1'; wait for 50 ns;
        L <= '0'; M <= '1'; N <= '0'; wait for 50 ns;
        L <= '0'; M <= '1'; N <= '1'; wait for 50 ns;
        L <= '1'; M <= '0'; N <= '0'; wait for 50 ns;
        L <= '1'; M <= '0'; N <= '1'; wait for 50 ns;
        L <= '1'; M <= '1'; N <= '0'; wait for 50 ns;
        L <= '1'; M <= '1'; N <= '1'; wait for 49 ns;
        L <= '0'; M <= '0'; N <= '0'; wait for 1 ns;
        finish;
    end process;
end sim;